language: java
install: true
jobs:
  include:
    - if: repo = alfasoftware/morf AND branch = master AND NOT type = pull_request
      name: "Test"
      script:
        - git fetch --unshallow --quiet
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U -Dsonar.host.url=https://sonarcloud.io
    - if: repo = alfasoftware/morf AND NOT branch = master AND NOT type = pull_request
      name: "Test"
      script:
        - git fetch --unshallow --quiet
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=$TRAVIS_BRANCH
    - if: repo = alfasoftware/morf AND type = pull_request
      name: "Test"
      script:
        - git fetch --unshallow --quiet
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test sonar:sonar -Pcoverage-per-test -B -U -Dsonar.host.url=https://sonarcloud.io -Dsonar.pullrequest.key=$TRAVIS_PULL_REQUEST -Dsonar.pullrequest.branch=$TRAVIS_PULL_REQUEST_BRANCH -Dsonar.pullrequest.base=$TRAVIS_BRANCH
    - if: repo = alfasoftware/morf AND branch = master AND NOT type = pull_request
      name: "Deploy"
      script:
        - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
        - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
        - mvn clean deploy --settings .maven-settings.xml -B -U -Prelease
    - if: NOT repo = alfasoftware/morf
      name: "Test"
      script:
        - mvn clean test -B -U
matrix:
  fast_finish: true
  include:
    - jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
